language: java


services:
  - postgresql

before_script:
  - psql -c 'create database foodNet;' -U postgres

addons:
  postgresql: "11"
  apt:
    packages:
      - postgresql-11
env:
  global:
    - PGPORT=5432