language: java

services:
  - postgresql

#addons:
#  postgresql: "11"
#  apt:
#    packages:
#      - postgresql-11
#      - postgresql-client-11
env:
  global:
    - PGPORT=5432
    - PGUSER=user
    - PGPASSWORD=test

before_script:
  - psql -c 'create database foodNet;' -U postgres
  - psql -c "CREATE USER user WITH PASSWORD 'test';" -U postgres
