language: java

services:
  - postgresql

#addons:
#  postgresql: "11"
#  apt:
#    packages:
#      - postgresql-11
#      - postgresql-client-11
env:
  global:
    - PGPORT=5433
    - PGUSER=postgres
    - PGPASSWORD=

before_script:
  - psql -c 'create database foodNet;' -U postgres