language: java

services:
  - postgresql

#addons:
#  postgresql: "11"
#  apt:
#    packages:
#      - postgresql-11
#      - postgresql-client-11
env:
  global:
    - PGPORT=5432
    - PGUSER=postgres
    - PGPASSWORD=
deploy:
  provider: heroku
  app: foodnet-htw
  api_key: d3c097de-d7cc-4074-a17f-352fc914810c

before_script:
  - psql -c 'create database foodNet;' -U postgres
