language: java

services:
  - postgresql

#addons:
#  postgresql: "11"
#  apt:
#    packages:
#      - postgresql-11
#      - postgresql-client-11
env:
  global:
    - PGPORT=5433
    - PGUSER=postgres
    - PGPASSWORD=

before_script:
  - sudo sed -i -e '/local.*peer/s/postgres/all/' -e 's/peer\|md5/trust/g' /etc/postgresql/*/main/pg_hba.conf
  - sudo service postgresql restart
  - sleep 1
  - psql -c 'create database foodNet;' -U postgres