language: java
services:
- postgresql
env:
  global:
  - PGPORT=5432
  - PGUSER=postgres
  - PGPASSWORD=
install:
  - gradle -q
  - gradle assemble
deploy:
  provider: heroku
  app: calabacin
  api_key:
    secure: MQS93gSDFtiXin/05uCoT4U38Zq0yOjF2A6HiKAQwKQ/igsmjVKiXWL3JpMzRmERQ8LTi2avlF0lClZntsBvla3MMSw/22npRxsdX0NQ7+oXmsUubxsVq0iFRb4mDGhpWvmlo3KndJx9s8W7db5w1kkr38blXSACPMdi5OED7u+8nM27T7bTXoVVND8TbOzGantDKw/vdOCTEC18aVAgIogsVuYhR8GSrhzikMU394WTok9JG1RJaRtzuZb5ZRyBvwlFr6Lad4L+LjM8bVDtwrh0GzvNH8GDJ+EHfvStoKvYZLJbqJE3U5kHC9fnDGLUKbqg37FtpXK0R+UJeg2nvXCsooqHdx9/exseAFrmlsaSBU5gzEh3gf62Y5kY95LrGgv8i5Oq+v8Tx9mx+0S9ns5VkKSIiDkU2AmyySgO81UVlvtUgFQ8qyq3xhhX0Ak0ER5pWwA77tn9mB+ZsNi2BdSyeAy9e4NrrGVNfo0sgfJfGZZXJgL8N5+M5Z3/la0csc1tYj8OSHLOquk4a3JwHYTdY+p2vMqNZxnFT++vJYPsqjMLUTiQaxr9yd4CUHpKKDkq3tZM7FlJrdiTznyCgTehriuPNGLMPVBhduvN7hwqJtai3tkNNlchopRovLxc5XcD1QRqZ6SR1z+8/e/nyzGDs7QRdyRtuM1dsCdzNIY=
before_script:
- psql -c 'create database foodNet;' -U postgres
